### ISSUE TITLE
Is "semver": "2 || 3 || 4" valid?

### ISSUE THREAD

**Issue by alexandernst** [npm/npmconf#57]
You have `"semver": "2 || 3 || 4",` in your package.json file. I'm having some difficulties with that. Is that actually a valid semver syntax?

**Comment by othiym23** [comment]
1. Yes, that's valid syntax for a semver range, and is written that way so as to be compatible with old versions of npm / semver, because this syntax has been supported for a long time.
2. This repo should be considered deprecated, because npmconf has been reincorporated into npm itself, and has since drifted from the code here pretty significantly.

**Comment by alexandernst** [comment]
Just one more question. How would that be translated to "modern" semver rules?

**Comment by othiym23** [comment]
`">=2 <5"`, but the syntax it has right now is fine (and arguably cleaner).
